"""Generator configuration, the in-memory instance, and small date/money helpers."""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from decimal import ROUND_HALF_EVEN, Decimal
from typing import Any

GENERATOR_VERSION = "2a.1"
COMPANY = "ExampleCo"  # fictional
SYNTHETIC_MARKER = (
    "SYNTHETIC DATA. ExampleCo and every supplier, person, contract and figure in this "
    "instance are fictional and generated by enterprise-evidence-bench; any resemblance to "
    "real entities is coincidental."
)


@dataclass(frozen=True)
class Scale:
    suppliers_per_category: int
    items_per_category: int
    pos_per_month: int
    max_lines: int
    planted_suppliers: int  # per scenario kind


SCALES: dict[str, Scale] = {
    "small": Scale(suppliers_per_category=3, items_per_category=4, pos_per_month=24,
                   max_lines=4, planted_suppliers=1),
    "default": Scale(suppliers_per_category=10, items_per_category=8, pos_per_month=1150,
                     max_lines=6, planted_suppliers=3),
}


@dataclass(frozen=True)
class Config:
    seed: int
    scale: str = "small"
    start: dt.date = dt.date(2024, 1, 1)
    end: dt.date = dt.date(2026, 6, 30)
    today: dt.date = dt.date(2026, 7, 15)  # the instance "benchmark today"; never wall clock

    def __post_init__(self) -> None:
        if self.scale not in SCALES:
            raise ValueError(f"unknown scale {self.scale!r}")
        if not (self.start < self.end < self.today):
            raise ValueError("require start < end < today")

    @property
    def sizes(self) -> Scale:
        return SCALES[self.scale]

    def as_record(self) -> dict[str, Any]:
        return {"seed": self.seed, "scale": self.scale, "start": self.start,
                "end": self.end, "today": self.today}


@dataclass(frozen=True)
class Section:
    kind: str
    heading: str
    body: str


@dataclass
class Document:
    doc_id: str
    version: int
    title: str
    classification: str
    scope_category: str | None
    scope_bu: str | None
    effective_from: dt.date
    effective_to: dt.date | None
    supersedes: str | None  # "doc_id@vN"
    authority: str  # contract | policy | memo | faq
    sections: list[Section]
    rendered: str = ""
    chunk_canaries: list[str] = field(default_factory=list)

    @property
    def key(self) -> str:
        return f"{self.doc_id}@v{self.version}"


@dataclass
class Instance:
    config: Config
    tables: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    documents: list[Document] = field(default_factory=list)
    principals: list[dict[str, Any]] = field(default_factory=list)
    assignments: list[dict[str, Any]] = field(default_factory=list)
    canaries: list[dict[str, Any]] = field(default_factory=list)
    sensitive_values: list[dict[str, Any]] = field(default_factory=list)
    scenarios: list[dict[str, Any]] = field(default_factory=list)


CENT = Decimal("0.01")


def money(x: Decimal) -> Decimal:
    return x.quantize(CENT, rounding=ROUND_HALF_EVEN)


def q(x: Decimal, places: int) -> Decimal:
    return x.quantize(Decimal(1).scaleb(-places), rounding=ROUND_HALF_EVEN)


def add_days(d: dt.date, n: int) -> dt.date:
    return d + dt.timedelta(days=n)


def month_starts(start: dt.date, end: dt.date) -> list[dt.date]:
    out = []
    d = dt.date(start.year, start.month, 1)
    while d <= end:
        out.append(d)
        d = dt.date(d.year + (d.month // 12), d.month % 12 + 1, 1)
    return out


def quarter_of(d: dt.date) -> str:
    return f"{d.year}Q{(d.month - 1) // 3 + 1}"


def quarter_bounds(quarter: str) -> tuple[dt.date, dt.date]:
    year, qn = int(quarter[:4]), int(quarter[5])
    first = dt.date(year, 3 * (qn - 1) + 1, 1)
    nxt = dt.date(year + (qn // 4), (3 * qn) % 12 + 1, 1)
    return first, nxt - dt.timedelta(days=1)


def days_in_month(d: dt.date) -> int:
    nxt = dt.date(d.year + (d.month // 12), d.month % 12 + 1, 1)
    return (nxt - dt.date(d.year, d.month, 1)).days
